### ISSUE TITLE
Where is deckdata_X.bin?

### ISSUE THREAD

**Issue by wenzdey** [nzxth2/YGO_LOTD_LE_DeckData_Editor#1]
Cool project. Is this to make creating custom decks easier?
Can you show how to get **deckdata_X.bin** files for Yu-Gi-Oh! Legacy of the Duelist Link Evolution?

**Comment by nzxth2** [comment]
There's a [guide](https://github.com/MoonlitDeath/Link-Evolution-Editing-Guide/wiki) linked in the credits. Basically you extract the game files using the python script on that page , then you can for example find deckdata_E.bin in YGO_2020/main/  

This tool alone won't help you do much, but in combination with the tools from my other repos you can modify existing duels (duelData_E.bin) and decks (.ydc files), or even try to add new content to the game I strongly suggest checking both links in the credits and joining [the discord](https://discord.gg/zWMKpRR) if you have questions.
